"""empty message

Revision ID: bac7f41a2ddd
Revises: 
Create Date: 2025-12-11 10:47:23.262888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bac7f41a2ddd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_code', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_user_code'), ['user_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_user_code'))
        batch_op.drop_column('user_code')

    # ### end Alembic commands ###
