"""empty message

Revision ID: bff9c4e9453d
Revises: bac7f41a2ddd
Create Date: 2025-12-18 02:47:22.584932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff9c4e9453d'
down_revision = 'bac7f41a2ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_code', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_studies_project_code'), ['project_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_studies_project_code'))
        batch_op.drop_column('project_code')

    # ### end Alembic commands ###
